import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { Playfair_Display, Fira_Code } from "next/font/google";
import { NavBar } from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={` ${geistSans.variable} ${playfairDisplay.variable} ${firaCode.variable} antialiased`}
      >
      <main className="max-h-screen flex items-center justify-center p-10 bg-fixed">
        <div
          className="w-full max-w-4xl h-[90vh] sm:h-[600px] overflow-y-scroll scrollbar-none bg-white/90 backdrop-blur-md rounded-xl shadow-xl border border-gray-200"
          style={{ scrollbarWidth: "none", msOverflowStyle: "none" }}
        >
          <style>
            {`
              div::-webkit-scrollbar {
                display: none;
              }
            `}
          </style>
          <NavBar />
          {children}
        </div>
      </main>
      </body>
    </html>
  );
}